
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Lakshya Soni
 */
public class tictactoe extends javax.swing.JFrame {

    /**
     * Creates new form tictactoe
     */
    int turn = 2;
    int[] buttonused = {0, 0, 0, 0, 0, 0, 0, 0, 0};
    int[] pOwon = {0, 0, 0, 0, 0, 0, 0, 0, 0};
    int[] pXwon = {0, 0, 0, 0, 0, 0, 0, 0, 0};
    
    intro in = new intro();

    public tictactoe() {
        initComponents();
    }
    
    boolean isDone(){
        for(int i=0; i<9; i++){
            if(buttonused[i]==0){
                return false;
            }
        }
        return true;
    }
    
    void restart(){
        for (int i = 0; i < 9; i++) {
            buttonused[i] = 0;
            pXwon[i] = 0;
            pOwon[i] = 0;
        }
        
        b0.setText("");
        b1.setText("");
        b2.setText("");
        b3.setText("");
        b4.setText("");
        b5.setText("");
        b6.setText("");
        b7.setText("");
        b8.setText("");
        
        label.setText("X's turn");
    }

    int pXwon() {

        for (int i = 0; i < 7; i = i + 3) {
            if (pXwon[i] == 1 && pXwon[i + 1] == 1 && pXwon[i + 2] == 1) {
                return 1;
            }
        }

        for (int i = 0; i < 3; i = i + 3) {
            if (pXwon[i] == 1 && pXwon[i + 3] == 1 && pXwon[i + 6] == 1) {
                return 1;
            }
        }

        if (pXwon[0] == 1 && pXwon[4] == 1 && pXwon[8] == 1) {
            return 1;
        }
        if (pXwon[2] == 1 && pXwon[4] == 1 && pXwon[6] == 1) {
            return 1;
        }

        return 0;
    }

    int pOwon() {

        for (int i = 0; i < 7; i = i + 3) {
            if (pOwon[i] == 1 && pOwon[i + 1] == 1 && pOwon[i + 2] == 1) {
                return 1;
            }
        }

        for (int i = 0; i < 3; i = i + 3) {
            if (pOwon[i] == 1 && pOwon[i + 3] == 1 && pOwon[i + 6] == 1) {
                return 1;
            }
        }

        if (pOwon[0] == 1 && pOwon[4] == 1 && pOwon[8] == 1) {
            return 1;
        }
        if (pOwon[2] == 1 && pOwon[4] == 1 && pOwon[6] == 1) {
            return 1;
        }

        return 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        b1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b0 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        b7 = new javax.swing.JButton();
        b8 = new javax.swing.JButton();
        restartbtn = new javax.swing.JButton();
        label = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        b1.setFont(new java.awt.Font("Bookman Old Style", 1, 48)); // NOI18N
        b1.setForeground(new java.awt.Color(0, 0, 102));
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        getContentPane().add(b1, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 85, 81, 76));

        b2.setFont(new java.awt.Font("Bookman Old Style", 1, 48)); // NOI18N
        b2.setForeground(new java.awt.Color(0, 0, 102));
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        getContentPane().add(b2, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 85, 81, 76));

        b0.setFont(new java.awt.Font("Bookman Old Style", 1, 48)); // NOI18N
        b0.setForeground(new java.awt.Color(0, 0, 102));
        b0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b0ActionPerformed(evt);
            }
        });
        getContentPane().add(b0, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 85, 81, 76));

        b3.setFont(new java.awt.Font("Bookman Old Style", 1, 48)); // NOI18N
        b3.setForeground(new java.awt.Color(0, 0, 102));
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });
        getContentPane().add(b3, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 167, 81, 76));

        b4.setFont(new java.awt.Font("Bookman Old Style", 1, 48)); // NOI18N
        b4.setForeground(new java.awt.Color(0, 0, 102));
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });
        getContentPane().add(b4, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 167, 81, 76));

        b5.setFont(new java.awt.Font("Bookman Old Style", 1, 48)); // NOI18N
        b5.setForeground(new java.awt.Color(0, 0, 102));
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });
        getContentPane().add(b5, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 167, 81, 76));

        b6.setFont(new java.awt.Font("Bookman Old Style", 1, 48)); // NOI18N
        b6.setForeground(new java.awt.Color(0, 0, 102));
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });
        getContentPane().add(b6, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 249, 81, 76));

        b7.setFont(new java.awt.Font("Bookman Old Style", 1, 48)); // NOI18N
        b7.setForeground(new java.awt.Color(0, 0, 102));
        b7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b7ActionPerformed(evt);
            }
        });
        getContentPane().add(b7, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 249, 81, 76));

        b8.setFont(new java.awt.Font("Bookman Old Style", 1, 48)); // NOI18N
        b8.setForeground(new java.awt.Color(0, 0, 102));
        b8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8ActionPerformed(evt);
            }
        });
        getContentPane().add(b8, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 249, 81, 76));

        restartbtn.setText("Restart Game");
        restartbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restartbtnActionPerformed(evt);
            }
        });
        getContentPane().add(restartbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, -1, -1));

        label.setBackground(new java.awt.Color(51, 51, 51));
        label.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        label.setForeground(new java.awt.Color(255, 255, 255));
        label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label.setText("X's turn");
        label.setAlignmentX(0.5F);
        getContentPane().add(label, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 130, 38));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Lakshya\\Projects\\Tic-Tac-Toe\\bg2.jpg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 400));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void b0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b0ActionPerformed
        // TODO add your handling code here:
        if (buttonused[0] == 0) {
            if (turn % 2 == 0) {
                turn++;
                
                b0.setText("X");
                buttonused[0] = 1;
                pXwon[0] = 1;

                label.setText("O's turn");
                
                if (pXwon() == 1) {
                    JOptionPane.showMessageDialog(this, in.p1 + " wins");
                    restart();
                }

            } else {
                turn++;
                
                b0.setText("O");
                buttonused[0] = 1;
                pOwon[0] = 1;

                label.setText("X's turn");
                
                if (pOwon() == 1) {
                    JOptionPane.showMessageDialog(this, in.p2 + " wins");
                    restart();
                }
             
            }
        }else{
            JOptionPane.showMessageDialog(this, "Invalid box!");
        }
        
        if(isDone()){
            JOptionPane.showMessageDialog(this, "It's a tie!");
            restart();
        }
    }//GEN-LAST:event_b0ActionPerformed

    
    private void restartbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restartbtnActionPerformed
        // TODO add your handling code here:
        restart();
        
    }//GEN-LAST:event_restartbtnActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        // TODO add your handling code here:
        
        if (buttonused[1] == 0) {
            if (turn % 2 == 0) {
                turn++;
                b1.setText("X");
                buttonused[1] = 1;
                pXwon[1] = 1;

                label.setText("O's turn");
                
                if (pXwon() == 1) {
                    JOptionPane.showMessageDialog(this, in.p1 + " wins");
                    restart();
                }
                
            } else {
                turn++;
                b1.setText("O");
                buttonused[1] = 1;
                pOwon[1] = 1;
                
                label.setText("X's turn");
                
                if (pOwon() == 1) {
                    JOptionPane.showMessageDialog(this, in.p2 + " wins");
                    restart();
                }
                 
            }
        }else{
            JOptionPane.showMessageDialog(this, "Invalid box!");
        }
        
        if(isDone()){
            JOptionPane.showMessageDialog(this, "It's a tie!");
            restart();
        }
    }//GEN-LAST:event_b1ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        // TODO add your handling code here:
        
        if (buttonused[2] == 0) {
            if (turn % 2 == 0) {
                turn++;
                b2.setText("X");
                buttonused[2] = 1;
                pXwon[2] = 1;

                label.setText("O's turn");
                
                if (pXwon() == 1) {
                    JOptionPane.showMessageDialog(this, in.p1 + " wins");
                    restart();
                }
           
            } else {
                turn++;
                b2.setText("O");
                buttonused[2] = 1;
                pOwon[2] = 1;

                label.setText("X's turn");
                
                if (pOwon() == 1) {
                    JOptionPane.showMessageDialog(this, in.p2 + " wins");
                    restart();
                }
               
            }
        }else{
            JOptionPane.showMessageDialog(this, "Invalid box!");
        }
        
        if(isDone()){
            JOptionPane.showMessageDialog(this, "It's a tie!");
            restart();
        }
    }//GEN-LAST:event_b2ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        // TODO add your handling code here:
        
        if (buttonused[3] == 0) {
            if (turn % 2 == 0) {
                turn++;
                b3.setText("X");
                buttonused[3] = 1;
                pXwon[3] = 1;

                label.setText("O's turn");
                
                if (pXwon() == 1) {
                    JOptionPane.showMessageDialog(this, in.p1 + " wins");
                    restart();
                }

            } else {
                turn++;
                b3.setText("O");
                buttonused[3] = 1;
                pOwon[3] = 1;

                label.setText("X's turn");
                
                if (pOwon() == 1) {
                    JOptionPane.showMessageDialog(this, in.p2 + " wins");
                    restart();
                }
               
            }
        }else{
            JOptionPane.showMessageDialog(this, "Invalid box!");
        }
        
        if(isDone()){
            JOptionPane.showMessageDialog(this, "It's a tie!");
            restart();
        }
    }//GEN-LAST:event_b3ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
        // TODO add your handling code here:
        
        if (buttonused[4] == 0) {
            if (turn % 2 == 0) {
                turn++;
                b4.setText("X");
                buttonused[4] = 1;
                pXwon[4] = 1;

                label.setText("O's turn");
                
                if (pXwon() == 1) {
                    JOptionPane.showMessageDialog(this, in.p1 + " wins");
                    restart();
                }
                

            } else {
                turn++;
                b4.setText("O");
                buttonused[4] = 1;
                pOwon[4] = 1;

                label.setText("X's turn");
                
                if (pOwon() == 1) {
                    JOptionPane.showMessageDialog(this, in.p2 + " wins");
                    restart();
                }
                
            }
        }else{
            JOptionPane.showMessageDialog(this, "Invalid box!");
        }
        
        if(isDone()){
            JOptionPane.showMessageDialog(this, "It's a tie!");
            restart();
        }
    }//GEN-LAST:event_b4ActionPerformed

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
        // TODO add your handling code here:
        if (buttonused[5] == 0) {
            if (turn % 2 == 0) {
                turn++;
                b5.setText("X");
                buttonused[5] = 1;
                pXwon[5] = 1;

                label.setText("O's turn");
                
                if (pXwon() == 1) {
                    JOptionPane.showMessageDialog(this, in.p1 + " wins");
                    restart();
                }
              
            } else {
                turn++;
                b5.setText("O");
                buttonused[5] = 1;
                pOwon[5] = 1;

                label.setText("X's turn");
                
                if (pOwon() == 1) {
                    JOptionPane.showMessageDialog(this, in.p2 + " wins");
                    restart();
                }
                
            }
        }else{
            JOptionPane.showMessageDialog(this, "Invalid box!");
        }
        
        if(isDone()){
            JOptionPane.showMessageDialog(this, "It's a tie!");
            restart();
        }
    }//GEN-LAST:event_b5ActionPerformed

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
        // TODO add your handling code here:
        
        if (buttonused[6] == 0) {
            if (turn % 2 == 0) {
                turn++;
                b6.setText("X");
                buttonused[6] = 1;
                pXwon[6] = 1;

                label.setText("O's turn");
                
                if (pXwon() == 1) {
                    JOptionPane.showMessageDialog(this, in.p1 + " wins");
                    restart();
                }
                
            } else {
                turn++;
                b6.setText("O");
                buttonused[6] = 1;
                pOwon[6] = 1;

                label.setText("X's turn");
                
                if (pOwon() == 1) {
                    JOptionPane.showMessageDialog(this, in.p2 + " wins");
                    restart();
                }
                
            }
        }else{
            JOptionPane.showMessageDialog(this, "Invalid box!");
        }
        
        if(isDone()){
            JOptionPane.showMessageDialog(this, "It's a tie!");
            restart();
        }
    }//GEN-LAST:event_b6ActionPerformed

    private void b7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b7ActionPerformed
        // TODO add your handling code here:
        
        if (buttonused[7] == 0) {
            if (turn % 2 == 0) {
                turn++;
                b7.setText("X");
                buttonused[7] = 1;
                pXwon[7] = 1;

                label.setText("O's turn");
                
                if (pXwon() == 1) {
                    JOptionPane.showMessageDialog(this,  in.p1 + " wins");
                    restart();
                }
                
            } else {
                turn++;
                b7.setText("O");
                buttonused[7] = 1;
                pOwon[7] = 1;

                label.setText("X's turn");
                
                if (pOwon() == 1) {
                    JOptionPane.showMessageDialog(this, in.p2 +" wins");
                    restart();
                }
                
            }
        }else{
            JOptionPane.showMessageDialog(this, "Invalid box!");
        }
        
        if(isDone()){
            JOptionPane.showMessageDialog(this, "It's a tie!");
            restart();
        }
    }//GEN-LAST:event_b7ActionPerformed

    private void b8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8ActionPerformed
        // TODO add your handling code here:
        
        if (buttonused[8] == 0) {
            if (turn % 2 == 0) {
                turn++;
                b8.setText("X");
                buttonused[8] = 1;
                pXwon[8] = 1;

                label.setText("O's turn");
                
                if (pXwon() == 1) {
                    JOptionPane.showMessageDialog(this, in.p1 + " wins");
                    restart();
                }
                
            } else {
                turn++;
                b8.setText("O");
                buttonused[8] = 1;
                pOwon[8] = 1;

                label.setText("X's turn");
                
                if (pOwon() == 1) {
                    JOptionPane.showMessageDialog(this, in.p2 + " wins");
                    restart();
                }
                
            }
        }else{
            JOptionPane.showMessageDialog(this, "Invalid box!");
        }
        
        if(isDone()){
            JOptionPane.showMessageDialog(this, "It's a tie!");
            restart();
        }
    }//GEN-LAST:event_b8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tictactoe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tictactoe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tictactoe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tictactoe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tictactoe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b0;
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton b8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel label;
    private javax.swing.JButton restartbtn;
    // End of variables declaration//GEN-END:variables
}
